add linters
lunakish/Portofolio pull request #1
Opened 2023-06-09 09:32 UTC by lunakish

2023-06-23 09:06 UTC, ciraganenicole requested changes
# ♻️ Required changes 

Hi @lunakish, first of all, congratulations on the work done so far 🎊 

- You'll need to solve the conflict before I go far with the review.

2023-06-23 10:15 UTC, ciraganenicole requested changes
# ♻️ Required changes

Congrats on the progress you made so far. There are some changes you must do before moving to the next part:

- First of all, in the mobile view, we have a hamburger menu and the background color is everywhere
- Secondly, you have to put the font size, and font family as the ones we find in the original design
- Colors must be the same as the ones in the design
- There are some blocks aligned at the start but you aligned them in the center, please correct that
- You forgot also to put a line under the text
- The "work" button is not styled

Here is pictures for illustration:
<img width="221" alt="Capture 1" src="https://github.com/lunakish/Portofolio/assets/72297212/a61ac421-5782-4520-b71a-0a3d01ab680c">                                                            <img width="146" alt="Capture 2" src="https://github.com/lunakish/Portofolio/assets/72297212/36160a4b-87b2-47fc-b4e6-0a1f74b4e054">

<img width="219" alt="Capture 3" src="https://github.com/lunakish/Portofolio/assets/72297212/a14cab4c-7500-48a5-98b3-5ab631bab55d">                                                            <img width="150" alt="Capture 4" src="https://github.com/lunakish/Portofolio/assets/72297212/f14d3451-8b72-4374-93ad-b2de80ca655e">

2023-06-23 10:32 UTC, ciraganenicole requested changes
## ♻️ Required changes in codes structure

You did well using the semantic tags in HTML but you didn't use them well:

-

2023-06-23 10:32 UTC, ciraganenicole commented on index.html
> +   </main>
This is a section, as the tag above is the header, this one should be a section, not the main

2023-06-23 10:32 UTC, ciraganenicole commented on index.html
> +
This is also a section because we can't have a footer in the middle of the body. Footer is the last part

2023-06-23 10:32 UTC, ciraganenicole commented on index.html
> +</section>
<ul> tag is already a block, no need to wrap it into a section tag. Instead of section class="link-list" ul li 
we can have ul class="link-list" li

2023-06-23 10:48 UTC, merged

2023-06-24 00:12 UTC, lunakish commented
if i remember well u said that i should work on desk design then we shall apply media query to make it responsive which i don't know for now , also i don't where this padding is coming from ...have tried but zero as result ... have made changes to what u mentioned ... thx coz am getting something