First
lunakish/Portofolio pull request #4
Opened 2023-06-23 23:33 UTC by lunakish

2023-06-26 06:34 UTC, ciraganenicole requested changes
Hi @Lynn-Kish , 
Congratulations, you made a lot of progress but there are still some changes you have to make, and after you'll move to the next step

<img width="181" alt="cap5" src="https://github.com/Lynn-Kish/Portofolio/assets/72297212/94a54a20-996d-421c-beb8-629a282b6b22">

- Please respect margins and padding, especially in the first paragraph
- Align the skills items at the start, not in the center
- Increase the size of social's icons
- Change the color of the work button

2023-06-26 06:34 UTC, ciraganenicole commented on index.html
> +<i class="fas fa-battery-full common-icon"></i>
Remove these lines of code, they are not needed

2023-06-26 06:34 UTC, ciraganenicole commented on index.html
>            </ul>
Replace the ul tag with div, this is not a list so no need to use ul, just use div and a tags

2023-06-26 06:34 UTC, ciraganenicole commented on index.html
Change these classnames to suit the bloc purpose (remove footer)

2023-06-26 21:56 UTC, Lynn-Kish commented
have made changes according to what u said ... hope u'll check on me as soon as possible

2023-06-30 20:06 UTC, ciraganenicole requested changes
Good work! But there are some changes you need to make:

- Titles, text, and buttons of the work section are aligned at the start, not the center
- Images are not visible, please, fix this

2023-07-03 06:41 UTC, ciraganenicole approved these changes
Hi @Lynn-Kish ,
Congratulations, you are good to go to the next step. You can merge this branch

2023-07-03 09:29 UTC, merged

2023-07-03 17:45 UTC, Lynn-Kish commented
thx